#pragma once

namespace proto {
enum PacketOpcode : unsigned char
{
    ID_USER_PACKET_ENUM = 134,
    ID_SHOW_MESSAGE_NOTIFY,
    ID_MATCHMAKING_REQ,
    ID_MATCHMAKING_RSP,
    ID_MATCH_CONFIRMATION_NOTIFY,
    ID_OPPONENT_DISCONNECTION_NOTIFY,
    ID_MATCH_FINISHED_NOTIFY,
};
}
